package com.kport.langueg.error;

public enum ErrorType {

    PARSE_IF_CONDITION_EMPTY,
    PARSE_IF_CONDITION_TUPLE,

    PARSE_WHILE_CONDITION_EMPTY,
    PARSE_WHILE_CONDITION_TUPLE,

    PARSE_FOR_MALFORMED_EXPRESSION,

    PARSE_FN_MALFORMED_PARAMETER,

    PARSE_FNTYPE_EXPECTED_LBRACK,


}
